### ISSUE TITLE
hello.go doesn't work 

### ISSUE THREAD

**Issue by kamoljan** [chai2010/webp#14]
hi @chai2010 

`hello.go` does not work any longer:

     ➜  src  cd github.com/chai2010/webp
     ➜  webp git:(master) go run hello.go
     width = 400, height = 301
     Metadata: err = webpGetMetadata: not found

Before it was generating `output.webp`?
But it works in my fork

**Comment by chai2010** [comment]
I think the `1_webp_ll.webp` dont have metadata, the `not found` maybe a normal returned message.
What is the output in your fork?
And do you have some webp data with metadata (need for test)?

Thanks.

**Comment by kamoljan** [comment]
in my fork:

    ➜  webp git:(master) go run hello.go
    width = 400, height = 301
    Save output.webp ok

However, it is the same file

yours:

    ➜  webp git:(master) pwd
    /Users/kamol/gocode/src/github.com/chai2010/web
    ➜  webp git:(master) md5 testdata/1_webp_ll.webp
    MD5 (testdata/1_webp_ll.webp) = 72962a1e7c00c017f3268aac2c2eccf0

mine:

    ➜  webp git:(master) ✗ pwd
    /Users/kamol/gocode/src/github.com/kamoljan/webp
    ➜  webp git:(master) ✗ md5 testdata/1_webp_ll.webp
    MD5 (testdata/1_webp_ll.webp) = 72962a1e7c00c017f3268aac2c2eccf0

**Comment by chai2010** [comment]
The hello.Go is OK.
The `Save output.webp ok` is removed in https://github.com/chai2010/webp/commit/804ad2572eb502a79300600c7b9ebb87fab14eb0

**Comment by kamoljan** [comment]
awesome!
