### ISSUE TITLE
Resize function?

### ISSUE THREAD

**Issue by badoet** [chai2010/webp#15]
is there going to be plan to add resizing function?
like the one from the cwebp
`cwebp -resize <width> <height>`
apparently resizing using cwebp give a clearer image compared to Lanczos3

**Comment by chai2010** [comment]
No plan to add resize.
You can try:
- https://godoc.org/golang.org/x/image/draw
- https://godoc.org/github.com/chai2010/image/draw

The [draw.Scaler](https://godoc.org/golang.org/x/image/draw#Scaler) is same as the resize.
