### ISSUE TITLE
webp.h: No such file or directory

### ISSUE THREAD

**Issue by vaniot-s** [chai2010/webp#36]
# github.com/chai2010/webp
./capi.go:26:10: fatal error: webp.h: No such file or directory
 #include "webp.h"
          ^~~~~~~~
compilation terminated.

**Comment by faroyam** [comment]
Hi, @vaniot-s! I've faced the same problem. Can you tell, how you solve it?

**Comment by trentrand** [comment]
Most likely your compiler is missing header files and shared objects. 
Try setting the `LIBRARY_PATH` and `CPATH` environment variables so that they include the missing file (e.g. `webp.h`).

For example, if you've installed webp using homebrew on MacOS 12, your configuration might look like:
```
export LIBRARY_PATH=$LIBRARY_PATH:/usr/local/lib:/opt/homebrew/lib/
export CPATH=$CPATH:/usr/local/include:/opt/homebrew/include/
```
