### ISSUE TITLE
Issue on package github.com/chai2010/webp v1.1.1 

### ISSUE THREAD

**Issue by Denes-cilwal** [chai2010/webp#69]
go run main.go 

# github.com/chai2010/webp
In file included from z_libwebp_src_enc_picture_csp_enc.c:9:
../../go/pkg/mod/github.com/chai2010/webp@v1.1.1/internal/libwebp-1.0.2/src/enc/picture_csp_enc.c:1002:40: warning: result of '2 ^ ALPHA_OFFSET' is 1; did you mean '1 << ALPHA_OFFSET' (8)? [-Wxor-used-as-pow]
../../go/pkg/mod/github.com/chai2010/webp@v1.1.1/internal/libwebp-1.0.2/src/enc/pi

**Comment by Pijushgupta** [comment]
Same issue, any update ? Thanks
